"""initial schema: ten tables

Revision ID: 6839f4e6f391
Revises: 
Create Date: 2026-08-28 17:40:56.439401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('bias_pp', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('customer', sa.String(length=128), nullable=False),
    sa.Column('end_customer', sa.String(length=128), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('design_status', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('eau_kpcs', sa.Float(), nullable=False),
    sa.Column('disty_asp', sa.Float(), nullable=False),
    sa.Column('resale_asp', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('competitor_part', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('confidence_rationale', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('matrix_a', sa.JSON(), nullable=False),
    sa.Column('rubric_factors', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('row_counts', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_value',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('param', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_value_opportunity_id'), 'field_value', ['opportunity_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_opportunity_id'), 'finding', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_finding_snapshot_id'), 'finding', ['snapshot_id'], unique=False)
    op.create_table('forecast',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('units_kpcs', sa.Float(), nullable=False),
    sa.Column('volume_revenue_k', sa.Float(), nullable=False),
    sa.Column('nre_revenue_k', sa.Float(), nullable=False),
    sa.Column('phasing_rule', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_opportunity_id'), 'forecast', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_forecast_snapshot_id'), 'forecast', ['snapshot_id'], unique=False)
    op.create_table('proposal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=False),
    sa.Column('base_confidence', sa.Float(), nullable=False),
    sa.Column('proposed_confidence', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_opportunity_id'), 'proposal', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_proposal_rubric_version_id'), 'proposal', ['rubric_version_id'], unique=False)
    op.create_table('state_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('from_value', sa.String(length=64), nullable=True),
    sa.Column('to_value', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_history_opportunity_id'), 'state_history', ['opportunity_id'], unique=False)
    op.create_table('confidence_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('base_confidence', sa.Float(), nullable=False),
    sa.Column('resulting_confidence', sa.Float(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_event_opportunity_id'), 'confidence_event', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_confidence_event_proposal_id'), 'confidence_event', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_confidence_event_rubric_version_id'), 'confidence_event', ['rubric_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confidence_event_rubric_version_id'), table_name='confidence_event')
    op.drop_index(op.f('ix_confidence_event_proposal_id'), table_name='confidence_event')
    op.drop_index(op.f('ix_confidence_event_opportunity_id'), table_name='confidence_event')
    op.drop_table('confidence_event')
    op.drop_index(op.f('ix_state_history_opportunity_id'), table_name='state_history')
    op.drop_table('state_history')
    op.drop_index(op.f('ix_proposal_rubric_version_id'), table_name='proposal')
    op.drop_index(op.f('ix_proposal_opportunity_id'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_index(op.f('ix_forecast_snapshot_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_opportunity_id'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_finding_snapshot_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_opportunity_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_field_value_opportunity_id'), table_name='field_value')
    op.drop_table('field_value')
    op.drop_table('snapshot')
    op.drop_table('rubric_version')
    op.drop_table('opportunity')
    op.drop_table('calibration')
    # ### end Alembic commands ###
